"""Provider-neutral corporate-action authority contracts."""

from automated_trading_bot.corporate_actions.model import (
    MAX_ACTION_LINEAGE_DEPTH,
    MAX_ACTION_LINEAGE_VERSIONS,
    ActionFamily,
    ActionOperation,
    ActionVersionId,
    AffectedDependency,
    AffectedDependencyDeclaration,
    CanonicalActionId,
    CanonicalCorporateAction,
    CorporateActionVersion,
    DependencyKind,
    DependencyState,
    IdentityBindingAssertion,
    LineageAuthorityAssertion,
    LineageValidationError,
    ProviderNativeActionRef,
    TemporalRoleSlot,
    TemporalRoleState,
    TemporalRoles,
    compute_action_facts_digest,
    create_action_version,
    create_canonical_action,
    validate_action_lineage,
)

__all__ = [
    "MAX_ACTION_LINEAGE_DEPTH",
    "MAX_ACTION_LINEAGE_VERSIONS",
    "ActionFamily",
    "ActionOperation",
    "ActionVersionId",
    "AffectedDependency",
    "AffectedDependencyDeclaration",
    "CanonicalActionId",
    "CanonicalCorporateAction",
    "CorporateActionVersion",
    "DependencyKind",
    "DependencyState",
    "IdentityBindingAssertion",
    "LineageAuthorityAssertion",
    "LineageValidationError",
    "ProviderNativeActionRef",
    "TemporalRoleSlot",
    "TemporalRoleState",
    "TemporalRoles",
    "compute_action_facts_digest",
    "create_action_version",
    "create_canonical_action",
    "validate_action_lineage",
]
